# Generated by Django 4.1 on 2023-03-13 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfData',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(max_length=64, unique=True, verbose_name='Type')),
                ('type_specific', models.IntegerField(blank=True, choices=[(0, 'Range(For INT)'), (1, 'Country code(For PhoneNumber)')], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('column_id', models.AutoField(primary_key=True, serialize=False)),
                ('column_name', models.TextField(max_length=128, verbose_name='Column name')),
                ('column_order', models.IntegerField(verbose_name='Order')),
                ('column_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='column_type', to='app.typeofdata', verbose_name='Type')),
            ],
            options={
                'ordering': ['column_order'],
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('schema_id', models.AutoField(primary_key=True, serialize=False)),
                ('schema_name', models.TextField(max_length=128, verbose_name='Name')),
                ('schema_column_separator', models.IntegerField(choices=[(0, 'Comma(,)'), (1, 'Semicolon(;)'), (2, 'Tab(    )'), (3, 'Space( )'), (4, 'Pipe(|)')], default=0, verbose_name='Column separator')),
                ('schema_string_character', models.IntegerField(choices=[(0, 'Double-quote (“)'), (1, "One-quote (')")], default=0, verbose_name='String character')),
                ('schema_columns', models.ManyToManyField(related_name='schema_columns', to='app.schemacolumn')),
                ('schema_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
