# Generated by Django 4.1 on 2023-03-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schema_schema_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='column_specific',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
